// App.tsx
import React, { useState } from 'react';
import { BookOpen, Clock, TrendingUp, Download, Sparkles, User, Target } from 'lucide-react';
import jsPDF from 'jspdf';

interface Course {
  title: string;
  description: string;
  timeline: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  prerequisites?: string[];
  outcomes?: string[];
}

interface RecommendationData {
  courses: Course[];
  motivation: string;
}

function App() {
  const [jobRole, setJobRole] = useState('');
  const [skills, setSkills] = useState('');
  const [recommendations, setRecommendations] = useState<RecommendationData | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const API_BASE = 'http://localhost:8000'; // change if deployed

  const generateRecommendations = async () => {
    if (!jobRole.trim()) return;

    setIsGenerating(true);
    try {
      const res = await fetch(`${API_BASE}/rag-llm`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          role: jobRole,
          user_skills: skills.split(',').map((s) => s.trim()),
        }),
      });

      if (!res.ok) {
        throw new Error(`Error: ${res.status}`);
      }

      const data = await res.json();
      setRecommendations({
        courses: Array.isArray(data.recommended_courses)
          ? data.recommended_courses.map((c: any) => ({
              title: c.title || c.name || '',
              description: c.description || '',
              timeline: c.timeline || '',
              difficulty: c.difficulty || 'Beginner',
              prerequisites: Array.isArray(c.prerequisites) ? c.prerequisites : c.prerequisites ? [c.prerequisites] : [],
              outcomes: Array.isArray(c.outcomes) ? c.outcomes : c.outcomes ? [c.outcomes] : [],
            }))
          : [],
        motivation: data.answer || '',
      });
    } catch (err) {
      console.error('Error fetching recommendations:', err);
      setRecommendations(null);
      alert('Failed to fetch recommendations. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  const getDifficultyColor = (difficulty: string) => {
    switch (difficulty) {
      case 'Beginner':
        return 'bg-emerald-100 text-emerald-800 border-emerald-200';
      case 'Intermediate':
        return 'bg-amber-100 text-amber-800 border-amber-200';
      case 'Advanced':
        return 'bg-rose-100 text-rose-800 border-rose-200';
      default:
        return 'bg-gray-100 text-gray-800 border-gray-200';
    }
  };

  // Function to generate PDF content
  const generatePDFContent = () => {
    if (!recommendations) return '';
    return `
UPSKILL ADVISOR AI - PERSONALIZED RECOMMENDATIONS

Job Role: ${jobRole}
Current Skills: ${skills}
Generated on: ${new Date().toLocaleDateString()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

COURSE RECOMMENDATIONS

${recommendations.courses
  .map(
    (course) => `
- ${course.title}

   Description: ${course.description}
   Timeline: ${course.timeline}
   Difficulty Level: ${course.difficulty}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`
  )
  .join('')}

MOTIVATION
${recommendations.motivation.split('. ').slice(0, 2).join('. ') + '.'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generated by Upskill Advisor AI
Ready for your learning journey!
    `.trim();
  };

  // Function to download the PDF
  const downloadPDF = () => {
    const doc = new jsPDF();
    const content = generatePDFContent();

    // Add content to the PDF
    doc.text(content, 10, 10);

    // Save the PDF
    doc.save(`upskill-recommendations-${jobRole.replace(/\s+/g, '-').toLowerCase()}.pdf`);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-50 via-white to-purple-50">
      <div className="container mx-auto px-4 py-8 max-w-6xl">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="flex items-center justify-center mb-6">
            <div className="bg-gradient-to-r from-indigo-500 to-purple-600 p-3 rounded-2xl mr-4">
              <Sparkles className="h-8 w-8 text-white" />
            </div>
            <div className="text-left">
              <h1 className="text-4xl font-bold text-gray-900 mb-1">Upskill Advisor AI</h1>
              <p className="text-lg text-indigo-600 font-medium">Your Personal Career Growth Assistant</p>
            </div>
          </div>
          <p className="text-lg text-gray-600 max-w-3xl mx-auto leading-relaxed">
            Get personalized course recommendations tailored to your role and skills. 
            Accelerate your career with AI-powered learning suggestions designed just for you.
          </p>
        </div>

        {/* Input Form */}
        <div className="max-w-2xl mx-auto mb-12">
          <div className="bg-white rounded-3xl shadow-xl p-8 border border-gray-100">
            <h2 className="text-2xl font-bold text-gray-800 mb-6 flex items-center">
              <div className="bg-indigo-100 p-2 rounded-lg mr-3">
                <User className="h-6 w-6 text-indigo-600" />
              </div>
              Tell me about yourself
            </h2>
            
            <div className="space-y-6">
              <div>
                <label htmlFor="jobRole" className="block text-sm font-semibold text-gray-700 mb-3">
                  What's the job role you're looking for?
                </label>
                <input
                  type="text"
                  id="jobRole"
                  value={jobRole}
                  onChange={(e) => setJobRole(e.target.value)}
                  className="w-full px-4 py-4 border border-gray-300 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition-all duration-200 text-gray-900 placeholder-gray-500"
                  placeholder="e.g., Software Engineer, Data Analyst, QA Engineer"
                  autoComplete="off"
                />
              </div>
              
              <div>
                <label htmlFor="skills" className="block text-sm font-semibold text-gray-700 mb-3">
                  What skills and technologies do you currently work with?
                </label>
                <textarea
                  id="skills"
                  value={skills}
                  onChange={(e) => setSkills(e.target.value)}
                  rows={4}
                  className="w-full px-4 py-4 border border-gray-300 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition-all duration-200 resize-none text-gray-900 placeholder-gray-500"
                  placeholder="e.g., React, JavaScript, Python, SQL, Docker, AWS, etc."
                />
              </div>
              
              <button
                onClick={generateRecommendations}
                disabled={!jobRole.trim() || isGenerating}
                className="w-full bg-gradient-to-r from-indigo-600 to-purple-600 text-white py-4 px-6 rounded-xl hover:from-indigo-700 hover:to-purple-700 disabled:from-gray-400 disabled:to-gray-400 disabled:cursor-not-allowed transition-all duration-300 flex items-center justify-center space-x-3 font-semibold text-lg shadow-lg"
              >
                {isGenerating ? (
                  <>
                    <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-white"></div>
                    <span>Analyzing your profile...</span>
                  </>
                ) : (
                  <>
                    <Target className="h-6 w-6" />
                    <span>Get My Learning Recommendations</span>
                  </>
                )}
              </button>
            </div>
          </div>
        </div>

        {/* Recommendations */}
        {recommendations && Array.isArray(recommendations.courses) && recommendations.courses.length > 0 ? (
          <div className="max-w-5xl mx-auto">
            <div className="bg-white rounded-3xl shadow-xl p-8 border border-gray-100">
              <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between mb-8 gap-4">
                <h2 className="text-3xl font-bold text-gray-800 flex items-center">
                  <div className="bg-green-100 p-2 rounded-lg mr-3">
                    <BookOpen className="h-7 w-7 text-green-600" />
                  </div>
                  Your Learning Path
                </h2>
                <div className="flex flex-col sm:flex-row gap-3">
                  <button
                    onClick={downloadPDF}
                    className="flex items-center justify-center space-x-2 px-6 py-3 bg-gradient-to-r from-indigo-600 to-purple-600 text-white rounded-xl hover:from-indigo-700 hover:to-purple-700 transition-all duration-200 font-medium shadow-lg"
                  >
                    <Download className="h-5 w-5" />
                    <span>Download PDF</span>
                  </button>
                </div>
              </div>
              <div className="space-y-6">
                {recommendations.courses.map((course, index) => (
                  <div key={index} className="border-2 border-gray-100 rounded-2xl p-6 hover:shadow-lg hover:border-indigo-200 transition-all duration-300 bg-gradient-to-r from-white to-gray-50">
                    <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between mb-4 gap-3">
                      <h3 className="text-xl font-bold text-gray-800 flex-1 leading-tight">
                        {course.title.toUpperCase()}
                      </h3>
                      <span className={`px-4 py-2 rounded-full text-sm font-semibold border ${getDifficultyColor(course.difficulty)} whitespace-nowrap`}>
                        {course.difficulty}
                      </span>
                    </div>
                    <p className="text-gray-600 mb-2 leading-relaxed text-lg">
                      <span className="font-medium text-gray-800">Why it's perfect for you:</span> {course.description}
                    </p>
                    {course.prerequisites && course.prerequisites.length > 0 && (
                      <div className="text-gray-700 mb-2 text-base">
                        <span className="font-semibold text-indigo-700">Prerequisites:</span>
                        <ul className="list-disc list-inside ml-4">
                          {course.prerequisites.map((pre, i) => (
                            <li key={i}>{pre}</li>
                          ))}
                        </ul>
                      </div>
                    )}
                    {course.outcomes && course.outcomes.length > 0 && (
                      <div className="text-gray-700 mb-2 text-base">
                        <span className="font-semibold text-green-700">Outcomes:</span>
                        <ul className="list-disc list-inside ml-4">
                          {course.outcomes.map((out, i) => (
                            <li key={i}>{out}</li>
                          ))}
                        </ul>
                      </div>
                    )}
                    <div className="flex items-center text-indigo-600 font-medium">
                      <Clock className="h-5 w-5 mr-2" />
                      <span>Estimated timeline: {course.timeline}</span>
                    </div>
                  </div>
                ))}
                <div className="bg-gradient-to-r from-green-50 to-emerald-50 rounded-2xl p-6 border-2 border-green-100 text-center">
                  <div className="flex justify-center mb-3">
                    <TrendingUp className="h-8 w-8 text-green-600" />
                  </div>
                  <p className="text-green-800 text-lg font-medium leading-relaxed mb-4">
                    {recommendations.motivation.split('. ').slice(0, 2).join('. ') + '.'}
                  </p>
                  <ul className="text-green-800 text-lg font-medium leading-relaxed list-disc list-inside">
                    {recommendations.courses.map((course) => (
                      <li key={course.title}>{course.title}</li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>
          </div>
        ) : recommendations && (!Array.isArray(recommendations.courses) || recommendations.courses.length === 0) ? (
          <div className="text-center text-lg text-gray-500 mt-8">No recommendations found. Please try again with different input.</div>
        ) : null}

        {/* Footer */}
        <div className="text-center mt-12 text-gray-500">
          <p className="text-sm">Built with ❤️ to help you grow your career</p>
        </div>
      </div>
    </div>
  );
}

export default App;
